
# Declaration statements
CTL-OPT=Ctl-Opt
DCL-C=Dcl-C
DCL-DS=Dcl-Ds
DCL-ENUM=Dcl-Enum
DCL-F=Dcl-F
DCL-PARM=Dcl-Parm
DCL-PI=Dcl-Pi
DCL-PR=Dcl-Pr
DCL-PROC=Dcl-Proc
DCL-S=Dcl-S
DCL-SUBF=Dcl-Subf
END-DS=End-Ds
END-ENUM=End-Enum
END-PI=End-Pi
END-PR=End-Pr
END-PROC=End-Proc
