javacDefaultEncoding.. = UTF-8
source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               plugin_de.properties,\
               plugin.properties,\
               plugin_nl.properties,\
               plugin_it.properties,\
               resources/,\
               lib/,\
               icons/
